export const products = [
  {
    id: 1,
    title: "Smartphone X",
    description: "Yangi avlod smartfoni, 128GB xotira, 6.5\" ekran",
    price: 799,
    rating: 4.5,
    image: "https://via.placeholder.com/300x200?text=Smartphone+X",
  },
  {
    id: 2,
    title: "Noutbuk Pro",
    description: "Ishlash uchun ideal noutbuk, 16GB RAM, 512GB SSD",
    price: 1299,
    rating: 4.8,
    image: "https://via.placeholder.com/300x200?text=Noutbuk+Pro",
  },
  {
    id: 3,
    title: "Aqlli soat",
    description: "Yugurish va sog'liqni kuzatish uchun aqlli soat",
    price: 199,
    rating: 4.2,
    image: "https://via.placeholder.com/300x200?text=Aqlli+Soat",
  },
  {
    id: 4,
    title: "Quloqchinlar",
    description: "Simsiz quloqchinlar, 30 soatgacha ishlash vaqti",
    price: 149,
    rating: 4.6,
    image: "https://via.placeholder.com/300x200?text=Quloqchinlar",
  },
  {
    id: 5,
    title: "Planshet",
    description: "10.5\" ekranli kuchli planshet, 256GB xotira",
    price: 599,
    rating: 4.4,
    image: "https://via.placeholder.com/300x200?text=Planshet",
  },
  {
    id: 6,
    title: "Televizor",
    description: "55\" 4K HDR Smart TV, Oled ekran",
    price: 899,
    rating: 4.7,
    image: "https://via.placeholder.com/300x200?text=Televizor",
  },
  {
    id: 7,
    title: "Fotokamera",
    description: "24.2MP, 4K video yozish qobiliyatiga ega",
    price: 749,
    rating: 4.3,
    image: "https://via.placeholder.com/300x200?text=Fotokamera",
  },
  {
    id: 8,
    title: "O'yin konsoli",
    description: "Yangi avlod o'yin konsoli, 1TB saqlash joyi",
    price: 499,
    rating: 4.9,
    image: "https://via.placeholder.com/300x200?text=O'yin+Konsoli",
  },
  {
    id: 9,
    title: "Printer",
    description: "Rangli lazer printer, ikki tomonlama chop etish",
    price: 299,
    rating: 4.1,
    image: "https://via.placeholder.com/300x200?text=Printer",
  },
  {
    id: 10,
    title: "Router",
    description: "Wi-Fi 6 texnologiyasiga ega yuqori tezlikli router",
    price: 129,
    rating: 4.0,
    image: "https://via.placeholder.com/300x200?text=Router",
  },
];